version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/taskdb
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: changeme
    volumes:
      - .:/app
    command: npm run dev

volumes:
  postgres_data:
